CREATE TABLE IF NOT EXISTS role (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS "user" (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(50)                             NOT NULL,
    password   VARCHAR(60)                             NOT NULL,
    first_name VARCHAR(50)                             NOT NULL,
    last_name  VARCHAR(50)                             NOT NULL,
    role_id    BIGINT                                  NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (role_id) REFERENCES role (id),
    UNIQUE (email)
);

CREATE INDEX ON "user" (email);

CREATE TABLE IF NOT EXISTS permission (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS "authorization" (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES role (id) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (permission_id) REFERENCES permission (id) ON UPDATE CASCADE ON DELETE NO ACTION
);